### ISSUE TITLE
[feature] cm level 20 talent suggestion

### ISSUE THREAD

**Issue by cannawen** [cannawen/dota-gsi-discord-bot#129]
If there is a phoenix, undying, veno, gyro, kotl, lich, pugna suggest to take attack speed talent at level 20

**Comment by cannawen** [comment]
Not sure if this feature is actually working - I haven't heard it.

**Comment by cannawen** [comment]
Might have been broken because #135 - see if it's fixed next deploy.

**Comment by cannawen** [comment]
```
2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] TypeError: enemies.reduce is not a function

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at hasEnemyWhereAttackSpeedIsUseful (/app/build/assistants/cmLevel20suggestion.js:23:20)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at Rule.when (/app/build/assistants/cmLevel20suggestion.js:31:9)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at Rule.when (/app/build/engine/rules/configurable.js:32:25)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at Rule.apply (/app/build/engine/Rule.js:17:18)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at /app/build/engine/Engine.js:46:33

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at Array.reduce (<anonymous>)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at applyRules (/app/build/engine/Engine.js:43:10)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at Engine.set (/app/build/engine/Engine.js:60:29)

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at /app/build/engine/Engine.js:62:26

2023-08-25T03:38:38.861 app[e2865644f6e686] yyz [info] at Array.forEach (<anonymous>)
```

**Comment by cannawen** [comment]
Heard the suggestion when playing vs a veno and weaver, seems good now.
